# Generated by Django 3.0.7 on 2020-06-22 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200620_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(blank=True, choices=[('3DP', '3D Printing'), ('ACR', 'Acrobatics'), ('ACT', 'Acting'), ('AMR', 'Amateur Radio'), ('ANI', 'Animation'), ('ANM', 'Anime'), ('AQS', 'Aquascaping'), ('AST', 'Astrology'), ('ASR', 'Astronomy'), ('BAK', 'Baking')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
