# Generated by Django 3.0.7 on 2020-06-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='interests',
            field=models.CharField(blank=True, choices=[('3DP', '3D Printing'), ('ACR', 'Acrobatics'), ('ACT', 'Acting'), ('AMR', 'Amateur Radio'), ('ANI', 'Animation'), ('ANM', 'Anime'), ('AQS', 'Aquascaping'), ('AST', 'Astrology'), ('ASR', 'Astronomy'), ('BAK', 'Baking')], max_length=3, unique=True),
        ),
    ]
