# Generated by Django 3.0.7 on 2020-06-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200622_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interests',
            old_name='interests',
            new_name='interest',
        ),
    ]
