# Generated by Django 3.0.7 on 2020-06-17 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('ACT', 'Activity'), ('ADV', 'Adventure'), ('HOB', 'Hobby'), ('SKI', 'Skill Development'), ('SOC', 'Social'), ('SPO', 'Sports')], max_length=3)),
                ('datetime', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skill', models.CharField(choices=[('JFF', 'Just for fun'), ('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], max_length=3)),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
