# Generated by Django 3.0.7 on 2020-08-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200812_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='coverimg',
            new_name='cover_img',
        ),
    ]
