version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
    - .:/code
    ports:
    - 8000:8000

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_PASSWORD: 'LT675mcl'
    volumes:
    - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: